version: '3.8'

services:
  swift-erlang-tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount source code for live development
      - ./Sources:/app/Sources:ro
      - ./Tests:/app/Tests:ro
    command: swift test
    environment:
      - SWIFT_DETERMINISTIC_HASHING=1
    
  swift-erlang-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Sources:/app/Sources:ro
      - ./.build:/app/.build
    command: swift build