name: Swift

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["6.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: vapor/swiftly-action@v0.2
        with:
          toolchain: ${{ matrix.swift }}
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: swift build
      - name: Run ETF tests
        run: swift test --filter ErlangActorSystemTests.ETFTests.
      - name: Run ErlangActorSystem tests
        # isolate test runs to avoid deadlocks
        run: swift test list | grep ErlangActorSystemTests.ErlangActorSystemTests. | xargs -n 1 swift test --filter